apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: backend
type: Opaque
data:
  aes-key: |
    <base64-encoded-content>
  rsa-private: |
    <base64-encoded-content>
  rsa-public: |
    <base64-encoded-content>
  ec-private: |
    <base64-encoded-content>
  ec-public: |
    <base64-encoded-content>




    base64 -w 0 src/main/resources/keys/aes_key.enc
----output should be streamed and pasted at <base64-encoded-content>



apply by this 
kubectl apply -f encryption-keys-secret.yaml



in deployments.yaml we will do like this volumeMounts:
  - name: encryption-keys
    mountPath: /app/keys
    readOnly: true

volumes:
  - name: encryption-keys
    secret:
      secretName: encryption-keys










      //bina iskee is command ki help le sakta ahe 

      kubectl create secret generic encryption-keys \
  --from-file=private.key=/path/to/private.key \
  --from-file=public.key=/path/to/public.key \
  -n backend







  ##finalll





  kubectl create secret generic encryption-keys \
  --from-file=aes_key.enc=UsBackend/src/main/resources/keys/aes_key.enc \
  --from-file=rsa_private_key.pem=UsBackend/src/main/resources/keys/rsa_private_key.pem \
  --from-file=rsa_public_key.pem=UsBackend/src/main/resources/keys/rsa_public_key.pem \
  --from-file=ec-private-pkcs8.pem=UsBackend/src/main/resources/keys/ec-private-pkcs8.pem \
  --from-file=ec-public.pem=UsBackend/src/main/resources/keys/ec-public.pem \
  -n backend



